from enum import Enum


class FtrackEnvironmentVariableEnum(Enum):
    FTRACK_SERVER = 'FTRACK_SERVER'
    FTRACK_API_USER = 'FTRACK_API_USER'
    FTRACK_API_KEY = 'FTRACK_API_KEY'
    FTRACK_APIKEY = 'FTRACK_APIKEY'
    FTRACK_EVENT_PLUGIN_PATH = 'FTRACK_EVENT_PLUGIN_PATH'
    FTRACK_API_SCHEMA_CACHE_PATH = 'FTRACK_API_SCHEMA_CACHE_PATH'
    HTTP_PROXY = 'HTTP_PROXY'
    HTTPS_PROXY = 'HTTPS_PROXY'
